### ISSUE TITLE
Independent Study Tutorials

### ISSUE THREAD

**Issue by kailah94** [BYU-IS-Media/independent_study#131]
When I clicked on the Independent Study Tutorials under the technical Support tab, videos automatically pop up.  If you click on multiple videos, they just stack on top of each other. The same happens under the tutoring section with Independent Study Tutorials.

**Comment by tessakohler1** [comment]
It looks like this page is working now, as far as I can tell. The way that the videos are uploaded in the code makes it so they expand when clicked on and collapse when a different one is clicked on. Is that what you mean by "they just stack on top of each other"? I'm going to close this issue for now though, because it seems like the page is functioning correctly. Feel free to re-open it if that's not the case, or if the video operation doesn't seem intuitive.
