### ISSUE TITLE
Counselor BYU Net ID Tutorial Broken Link

### ISSUE THREAD

**Issue by nrust6** [BYU-IS-Media/independent_study#150]
Under the financial aid tab, select High School Scholarship, then click [here] for a tutorial to create one (netID). This link takes you to the website home page instead of the tutorial page. https://is.byu.edu/site/support/counselortutorial.cfm

**Comment by tessakohler1** [comment]
Hey, we changed the wording here. It now links them to the "create a counselor account" form instead of a tutorial. The tutorial was removed because it was no longer valid (the process to do it changed). This new form is the replacement, so the textual edit reflects the current state of things... please take a look and we can adjust if needed!

 https://is.byu.edu/support/scholarship

[[Written by Luke]]
