### ISSUE TITLE
AP Courses Page

### ISSUE THREAD

**Issue by jvthomas93** [BYU-IS-Media/independent_study#22]
Both the NCAA and AP courses pages are very different on the old and new sites. Which do we use?

**Comment by tessakohler1** [comment]
I just updated the NCAA page to the same content as the current page, but I'm not sure about the AP courses page.

**Comment by luke80** [comment]
A number of the AP courses were expired. I think that's why they are not showing on the live site.

For now I would suggest we limit the list to those that are on the live site. In the future we'll want to make this a "live" list of courses that are AP, automatically generated. If we have time I could teach you how to do this, as lists like this one are going to become a main staple of marketing (you'll want to be able to make "package" pages of courses for different purposes).

Choose which solution you like; shorten the list or learn something complicated which we may not have time or energy for but Luke is willing.

**Comment by tessakohler1** [comment]
I'll work on this today.

**Comment by tessakohler1** [comment]
Updated in Drupal.
